version: '3.8'

networks:
  dev-agriness:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/16
services:
  db:
    image: mysql:8.0.20
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: agrinessdb
    ports:
      - "3306:3306"
    networks:
      dev-agriness:
        ipv4_address: 172.10.1.1
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=agrinessdb
      - MYSQL_USER=root

  java:
    build: 
      context: .
      dockerfile: Dockerfile      
    image: jboss
    container_name: jboss
    ports:
      - "8080:8080"
    volumes:
      - './deploy:/opt/jboss/wildfly/standalone/deployments'
    networks:
      - dev-agriness

